### CPP compiler wrapper
CXX=mpicxx

### Optimization flags
FFLAGS=-O3


###########################
all:  pi_mpi.exec
##########################

##  all reduce
pi_mpi.exec : pi_mpi.cpp
	$(CXX) $(FFLAGS) pi_mpi.cpp -o pi_mpi.exec







