######################################################################
all: pi_finite_diff.cpp.exec
####################################################################### 

## Example 1
pi_finite_diff.cpp.exec : pi_finite_diff.cpp
	g++ pi_finite_diff.cpp -o pi_finite_diff.cpp.exec

####################################################################### 

clean :
	rm -f *.exec
